package com.executionagent.trace;

import com.executionagent.agent.ExecutionAgent;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/**
 * Generates a replay bash script from agent execution trace.
 * Mirrors Python trace_to_bash.py.
 */
public class TraceToBash {

    private static final Logger LOG = LoggerFactory.getLogger(TraceToBash.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    /**
     * Save a bash script that replays the agent's execution trace.
     */
    public static void saveBashScriptFromAgent(ExecutionAgent agent, Path outputPath) throws IOException {
        String script = generateBashScript(agent);
        Files.writeString(outputPath, script, StandardCharsets.UTF_8);
        new File(outputPath.toString()).setExecutable(true);
        LOG.info("Replay script saved to: {}", outputPath);
    }

    private static String generateBashScript(ExecutionAgent agent) {
        StringBuilder sb = new StringBuilder();
        sb.append("#!/bin/bash\n");
        sb.append("# Replay trace generated by ExecutionAgent\n");
        sb.append("set -e\n\n");

        // Cleanup trap
        sb.append("cleanup() {\n");
        sb.append("  if [ -n \"$CONTAINER_ID\" ]; then\n");
        sb.append("    echo 'Cleaning up container...'\n");
        sb.append("    docker rm -f \"$CONTAINER_ID\" >/dev/null 2>&1 || true\n");
        sb.append("  fi\n");
        sb.append("  if [ -n \"$IMAGE_TAG\" ]; then\n");
        sb.append("    docker rmi -f \"$IMAGE_TAG\" >/dev/null 2>&1 || true\n");
        sb.append("  fi\n");
        sb.append("}\n");
        sb.append("trap cleanup EXIT\n\n");

        String imageTag = agent.dockerTag != null && !agent.dockerTag.isBlank()
                ? agent.dockerTag : "replay-" + agent.projectPath.replace("/", "-");
        sb.append("IMAGE_TAG=\"").append(imageTag).append("\"\n");
        sb.append("CONTAINER_ID=\"\"\n\n");

        // Write files first
        for (String[] wf : agent.writtenFiles) {
            if (wf.length < 4) continue;
            String target = wf[0];
            String location = wf[1];
            String path = wf[2];
            String content = wf[3];

            if ("dockerfile".equalsIgnoreCase(target)) {
                // Build image from Dockerfile
                sb.append("# Write Dockerfile and build image\n");
                sb.append("TMPDIR=$(mktemp -d)\n");
                sb.append("cat > \"$TMPDIR/Dockerfile\" <<'DOCKERFILE_EOF'\n");
                sb.append(content).append("\n");
                sb.append("DOCKERFILE_EOF\n\n");
                sb.append("echo 'Building Docker image...'\n");
                sb.append("docker build -t \"$IMAGE_TAG\" \"$TMPDIR\"\n");
                sb.append("echo 'Starting container...'\n");
                sb.append("CONTAINER_ID=$(docker run -d \"$IMAGE_TAG\" tail -f /dev/null)\n\n");

            } else if ("container".equals(location)) {
                // Write file to container
                sb.append("# Write file to container: ").append(path).append("\n");
                sb.append("docker exec \"$CONTAINER_ID\" bash -lc ");
                String mkdirCmd = "mkdir -p " + shellQuote(path.contains("/")
                        ? path.substring(0, path.lastIndexOf('/')) : "/tmp");
                sb.append(shellQuote(mkdirCmd)).append("\n");

                sb.append("cat > /tmp/_replay_file_content <<'FILE_EOF'\n");
                sb.append(content).append("\n");
                sb.append("FILE_EOF\n");
                sb.append("docker cp /tmp/_replay_file_content \"$CONTAINER_ID\":").append(path).append("\n\n");
            }
        }

        // Replay terminal commands
        for (Object[] entry : agent.commandsAndSummary) {
            String callStr = (String) entry[0];
            if (!callStr.startsWith("Call to tool linux_terminal")) continue;

            try {
                String argsJson = callStr.substring("Call to tool linux_terminal with arguments ".length());
                @SuppressWarnings("unchecked")
                Map<String, Object> args = MAPPER.readValue(argsJson, Map.class);
                String cmd = (String) args.get("command");
                if (cmd == null || cmd.isBlank()) continue;

                sb.append("# ").append(cmd.substring(0, Math.min(80, cmd.length())).replace("\n", " ")).append("\n");
                if (agent.containerId != null && !agent.containerId.isBlank()) {
                    sb.append("docker exec \"$CONTAINER_ID\" bash -lc ").append(shellQuote(cmd)).append("\n");
                } else {
                    sb.append("bash -lc ").append(shellQuote(cmd)).append("\n");
                }
                sb.append("\n");
            } catch (Exception ignored) {}
        }

        sb.append("echo 'Replay complete!'\n");
        return sb.toString();
    }

    private static String shellQuote(String s) {
        return "'" + s.replace("'", "'\\''") + "'";
    }
}
